[package]
edition.workspace = true
name = "e2e-tests"
publish = false
version = "0.0.0"
rust-version.workspace = true

[dependencies]
sudo-test.path = "../sudo-test"

[features]
apparmor = ["sudo-test/apparmor"]
